name: API Tests with Postman

on:
  push:
    branches:
      - master

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start API container
        env:
          DB_NAME: testdb
          DB_USER: testuser
          DB_PASSWORD: testpassword
        run: |
          docker compose run --rm app sh -c "python manage.py migrate && python manage.py runserver"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run ./postman/collection.json \
            -e ./postman/environment.json
