name: API Tests with Postman

on:
  push:
    branches:
      - master

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        env:
          DB_NAME: testdb
          DB_USER: testuser
          DB_PASSWORD: testpassword

      - name: Start API container
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 15

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run ./postman/collection.json \
            -e ./postman/environment.json

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml down
