name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  SERVICE_NAME: mysite-service
  PROJECT_ID: noted-acronym-451221-n4
  REGION: us-central1
  APP: app
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/${PROJECT_ID}/${APP}

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
        - name: 'Checkout'
          uses: 'actions/checkout@v3'

        - name: 'Google auth'
          id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ env.PROJECT_ID }}

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'

        - name: 'Configure Docker'
          run:  |
            gcloud init
            gcloud auth configure-docker us-central1-docker.pkg.dev

        - name: 'Build the Docker image'
          run: |
            docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest .
            docker push ${{ env.DOCKER_IMAGE_URL }}:latest

        - name: 'Deploy the Docker image to Cloud Run'
          run: |
            gcloud run deploy ${{ env.SERVICE_NAME }} \
              --image ${{ env.DOCKER_IMAGE_URL }}:latest \
              --platform managed \
              --region ${{ env.REGION }} \
              --allow-unauthenticated
