name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  SERVICE_NAME: mysite
  PROJECT_ID: noted-acronym-451221-n4
  REGION: northamerica-south1
  APP: mysite
  DOCKER_IMAGE_URL: northamerica-south1-docker.pkg.dev/noted-acronym-451221-n4/mysite/image
  SERVICE_ACCOUNT: github-actions-service-account@noted-acronym-451221-n4.iam.gserviceaccount.com

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
        - name: 'Checkout'
          uses: 'actions/checkout@v3'

        - name: 'Google auth'
          id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ env.PROJECT_ID }}

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'

        - name: 'Configure Docker'
          run:  |
            gcloud init
            gcloud auth configure-docker northamerica-south1-docker.pkg.dev

        - name: 'Build the Docker image'
          run: |-
            docker build \
                --tag "${{ env.DOCKER_IMAGE_URL }}" \
                --file Dockerfile .
            docker push ${{ env.DOCKER_IMAGE_URL }}

        - name: 'Deploy the Docker image to Cloud Run'
          run: |
            gcloud run deploy ${{ env.SERVICE_NAME }} \
              --image ${{ env.DOCKER_IMAGE_URL }} \
              --platform managed \
              --region ${{ env.REGION }} \
              --allow-unauthenticated
